[username]
format = "[$user]($style) "
disabled = false
show_always = true

[hostname]
format = "at [$hostname]($style) in "
disabled = false
ssh_only = false

[directory]
truncate_to_repo = true
fish_style_pwd_dir_length = 1
truncation_length = 2